CarMarket.Web/Models/SearchcarViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace CarMarket.Web.Models
{
    public class SearchcarViewModel
    {
        [Display(Name = "Car Brand")]
        public string CarModel { get; set; }
    }
}

CarMarket.Web/Controllers/CRUDCarController.cs
namespace CarMarket.Web.Controllers
{
    using CarMarket.Data;
    using Domain;
    using Microsoft.AspNet.Identity;
    using Models;
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Web.Mvc;

    public class CRUDCarController : BaseController
    {
        [Authorize]
        public ActionResult Create()
        {
            var model = new AddCarViewModel();
            return View(model);
        }

        [Authorize]
        [HttpPost]
        public ActionResult Create(AddCarViewModel m)
        {
            //var v = Request.Params;
            if (ModelState.IsValid)
            {
                var user = User.Identity.GetUserId();
                byte[] content = null;
                string fileExtension = null;
                if (m.UploadedImage != null)
                {
                    using (var memory = new MemoryStream())
                    {
                        m.UploadedImage.InputStream.CopyTo(memory);
                        content = memory.GetBuffer();
                        fileExtension = m.UploadedImage.FileName.Split(new[] { '.' }).Last();

                    }
                }

                Car car = new Car
                {
                    Price = m.Price,
                    Model = new CarModel { Name = m.ModelName, Year = m.ModelYear, Brand = new Brand { Name = m.BrandName } },
                    Color = m.Color,
                    Mileage = m.Mileage,
                    Transmission = m.Transmission,
                    Fuel = m.Fuel,
                    NumberOfCylinders = m.NumberOfCylinders,
                    SellerNotes = m.SellerNotes,
                    ListingDate = DateTime.Now,
                    SellerId = user,
                    Image = new Image { Content = content, FileExtension = fileExtension }
                };

                this.Data.Cars.Add(car);
                this.Data.SaveChanges();
            }

            return RedirectToAction("Index", "Home");
        }

    }
}

CarMarket.Web/Controllers/CarController.cs
namespace CarMarket.Web.Controllers
{
    using System.Linq;
    using System.Web;
    using System.Web.Mvc;
    using CarMarket.Web.Models;

    public class CarController : BaseController
    {
       
        public ActionResult CarDetails(int id)
        {
            var viewModel = this.Data.Cars.All().Where(x => x.CarId == id)
                .Select(x => new CarDetailsViewModel
                {
                    Id = x.CarId,
                    Price = x.Price,
                    ListingDate = x.ListingDate,
                    Brand = x.Model.Brand.Name,
                    Model = x.Model.Name,
                    ModelYear = x.Model.Year,
                    ImageId = x.Image.ImageId,
                    Color = x.Color,
                    Mileage = x.Mileage,
                    Transmission = x.Transmission,
                    Fuel = x.Fuel,
                    NumberOfCylinders = x.NumberOfCylinders,
                    SellerEmail = x.Seller.Email,
                    SellerPhone = x.Seller.PhoneNumber,
                    SellerNotes = x.SellerNotes

                }).FirstOrDefault();

            return View(viewModel);
        }

        public ActionResult Image(int id)
        {
            var image = this.Data.Images.GetById(id);
            if (image == null)
            {
                throw new HttpException(404, "Image not found");
            }

            return File(image.Content, "image/" + image.FileExtension);
        }
    }
}

CarMarket.Web/Controllers/SearchController.cs
using CarMarket.Data;
using CarMarket.Domain;
using CarMarket.Web.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CarMarket.Web.Controllers
{
    public class SearchController : BaseController
    {

        [HttpGet]
        public ActionResult Search()
        {
            SearchcarViewModel model = new SearchcarViewModel();
            return View(model);
        }
        [HttpPost]
        public ActionResult Search(SearchcarViewModel model)
        {
            if (ModelState.IsValid)
            {
                string carBrand = Convert.ToString(model.CarModel);
                var db = new CarMarketDbContext();
                IEnumerable<Car> cars = db.Cars
                    .Where(x => x.Model.Brand.Name == carBrand
                    || x.Model.Name == carBrand)
                    .ToList();
                return PartialView("_SearchCar", cars);
            }
            return Json("Error");
        }
    }
}

CarMarket.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Car Market</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Car Market", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("Add Car", "Create", "CRUDCar")</li>
                    <li>@Html.ActionLink("Search Car", "Search", "Search")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Car Market</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

CarMarket.Web/Views/Shared/_SearchCar.cshtml
@model IEnumerable<CarMarket.Domain.Car>



<div class="row">
    @foreach (var car in Model)
    {

        <div class="row">
            <div class="col-lg-12">
                <h1 class="page-header">
                    @car.Model.Brand.Name
                    <small>@car.Model.Name</small>
                </h1>
            </div>
        </div>
        
        <div class="col-md-6">
            <img src="@Url.Action("Image", "Car", new { id = car.ImageId})" class="img-responsive" />
        </div>
        <div class="col-md-6">
            <h2 class="text-danger">$@car.Price</h2>
            <h3>Vehicle Details</h3>
            <ul class="list-group">
                <li class="list-group-item">Year: <p class="pull-right text-info">@car.Model.Year</p></li>
                <li class="list-group-item">Color: <p class="pull-right text-info">@car.Color</p></li>
                <li class="list-group-item">Mileage: <p class="pull-right text-info">@car.Mileage</p></li>
                <li class="list-group-item">Transmission: <p class="pull-right text-info">@car.Transmission</p></li>
                <li class="list-group-item">Fuel: <p class="pull-right text-info">@car.Fuel</p> </li>
                <li class="list-group-item">Cylinders: <p class="pull-right text-info">@car.NumberOfCylinders</p> </li>
            </ul>           
            <br />
        </div>
       


    }
    
</div>